name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          check-latest: true

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          # Activate the virtual environment
          source venv/bin/activate
          
          # Create a deployment package directory
          mkdir -p package

          # Install dependencies into the "package" directory
          pip install -r requirements.txt --target ./package

          # Copy the necessary application files (e.g., app.py, any additional modules)
          cp app.py ./package
          cd package

          # Zip the package for deployment
          zip -r ../function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name python-lambda-test --zip-file fileb://function.zip
